### PR TITLE
Updated OAuth1 docs (#15)

### PR DESCRIPTION
**Pull request by nfgrilo**
- replaced field list by table
- updated screenshots

### CODE REVIEW

**Comment by mittsh** [comment]
@nfgrilo can you please also update the doc for the new RSA-SHA1 signature? thanks!

**Comment by nfgrilo** [comment]
Would it make sense to reuse existing field table to add specific info for RSA-SHA1 algorithm?

Also, do you think is too much add an additional screenshot showing a RSA configuration?

**Comment by mittsh** [comment]
@nfgrilo as RSA isn't so common, I don't think we need an extra screenshot, but why not... I'd just add a line about it, or maybe a table with just the 2 field that changes for RSA.

**Comment by nfgrilo** [comment]
Do you think this is "over-kill"?

* referenced `RSA-SHA1`when appropriate
* added more detail to the description of each field

screen shot 2015-10-27 at 11 54 55

**Comment by mittsh** [comment]
It's nice like this. Organized and well documented for each param.

**Comment by nfgrilo** [comment]
Done!

**Comment by mittsh** [comment]
:+1:

**Pull request merged**
